[package]
name = "base64"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Andolf"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
clap = { version = "3.2.22", features = ["cargo", "suggestions"] }
